name: springfydrt
description: "App musicianas"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.8

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  http: ^1.6.0
  path_provider: ^2.1.2
  just_audio: ^0.9.36
  audio_service: ^0.18.2
  rxdart: ^0.27.7
  audioplayers: ^5.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: "^0.11.0"

flutter:
  uses-material-design: true
  assets:
    - assets/

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon.jpg"
