name: springfydrt
description: "App musicianas"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.8

dependencies:
  flutter:
    sdk: flutter

  web_socket_channel: ^2.4.0
  cupertino_icons: ^1.0.8
  http: ^1.6.0
  path_provider: ^2.1.2

  rxdart: ^0.27.7
  audio_service: ^0.18.2
  just_audio: ^0.9.36
  audioplayers: ^5.2.1
  path: ^1.9.1
  flutter_login: ^6.0.0
  flutter_secure_storage: ^9.2.2
  jwt_decoder: ^2.0.1
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: "^0.11.0"

flutter:
  uses-material-design: true
  assets:
    - assets/

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon.png"
